Feature/do 1598 user manual
Cofinity-X/cofinity-x-ba-traceability-foss pull request #103
Opened 2023-12-18 10:08 UTC by JanKewitz

2023-12-18 13:44 UTC, hgo-ds reviewed
**Clarification:**

- Some of the links can be accessed only for signed in users.
  i.e.
  Available roles: https://portal.int.demo.catena-x.net/appusermanagement/3bbc88ae-5f0d-45cb-ab3e-8c7602ff58b4
  Role details: https://portal.int.demo.catena-x.net/role-details
   - is this on purpose?
   - would we need a hint on that?
   - Would there be an open alternative available

- Is it acceptable to use brand names such as BMW, Hella, Philips or Osram in the example screenshots?

- This section needs a punctuation mark (ca. lines 315 & 416):
  ```
  Supplier parts
  Detailed information for child parts assigned to a notification
  ```

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +A yellow border indicates that the part is a piece of a batch.
**Suggestion:**

Check with UI team probably as there might be more colors, i.e. for `UNKNOWN` or `JUSTINSEQUENCE`:

A quick example:

![image](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/145972012/3d19dbbb-b2f4-4561-9bc2-6377a59fcf8e)

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Selection will enable you to create a quality investigation (notification) to your supplier.
**Clarification:**

This is valid for AsBuilt only?

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
>  Customer Parts that are in a quality alert are highlighted yellow.
**Clarification:**

Still true?

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
>  image:https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/user-guide/notification-drafts.png[] Received investigations.
**Clarification:**

Is this nice symbol available already or is it still in progress?
Can't find it in the UI.

Applies to several positions.

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Queued investigations are investigations that were created by a user in your company but are not yet sent to the supplier until a supervisor approves them.
**Suggestion:**

An example screen containing a queued investigation would be helpful.

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
>  A pop-up will notify you if the status transition was successful.
**Suggestion:**

Add some explanation on the images what exactly happens there? Or would it fit better in the paragraph above?

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Queued & Requested quality alerts on the other hand are quality alerts that were requested by your company and that are sent to the supplier after you detected a defect, or you have a request on a sp
**Clarification:**

Would an alert be sent to a customer rather than a supplier?

2023-12-18 13:44 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Received quality alerts by a customer specify that the given customer has found a defect or has a request for you to investigate on a specific part/ batch on your side and waits for your feedback.
**Clarification:**

Isn't it more that a supplier sends quality alerts?

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
>  You can sort the table by clicking on the table header. On the first click, the table is sorted in ascending order, on the second click the table is sorted in descending order. If the table is alread
**Suggestion:**

Use a comma before 'and' since it connects two independent clauses.

```suggestion
You can sort the table by clicking on the table header. On the first click, the table is sorted in ascending order, on the second click the table is sorted in descending order. If the table is already sorted, and you hold shift while clicking on another table header. The table is sorted primarily by the already given column but is then ordered secondly by the specified column. You can sort by as many columns as you desire.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
>  You can select which columns are displayed by clicking on the settings icon on the top right corner of the table.
**Suggestion:**

The usual preposition to use with "corner" is "in", not "on". Did you mean in the top right corner?

```suggestion
You can select which columns are displayed by clicking on the settings icon in the top right corner of the table.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Clicking on the three dots menu on the right side of a quality alert entry opens the quality alert context menu. In the context menu, users can open the detailed of the given quality alert. Superviso
**Suggestion:**

Typo?

```suggestion
Clicking on the three dots menu on the right side of a quality alert entry opens the quality alert context menu. In the context menu, users can open the details of the given quality alert. Supervisor can additionally update the status of the given quality alert. Only possible status update actions will be shown in the menu.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +If you want to discard your changes, simply press you "ESC" - button, click anywhere else except in the dialog or close it explicitely with the close icon on the upper right of the dialog.
**Suggestion:**

Typo?

```suggestion
If you want to discard your changes, simply press you "ESC" - button, click anywhere else except in the dialog or close it explicitly with the close icon on the upper right of the dialog.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +It is possible to hide/show all columns by clicking on the "All"- checkbox.
**Suggestion:**

```suggestion
It is possible to hide/show all columns by clicking on the "All"-checkbox.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +You can sort the table by clicking on the table header. On the first click, the table is sorted in ascending order, on the second click the table is sorted in descending order. If the table is alread
**Suggestion:**

Use a comma before 'and' since it connects two independent clauses.

```suggestion
You can sort the table by clicking on the table header. On the first click, the table is sorted in ascending order, on the second click the table is sorted in descending order. If the table is already sorted, and you hold shift while clicking on another table header. The table is sorted primarily by the already given column but is then ordered secondly by the specified column. You can sort by as many columns as you desire.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +You can select which columns are displayed by clicking on the settings icon on the top right corner of the table.
**Suggestion:**

The usual preposition to use with "corner" is "in", not "on". Did you mean in the top right corner?

```suggestion
You can select which columns are displayed by clicking on the settings icon in the top right corner of the table.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +*German
**Fix:**

Leave a space between asterisk and list item.

```suggestion
* English
* German
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +With administrator authorization, the user is primarily able to configure the technical configuration of the EDC connection. From a technical perspective, the admin only has read authorization for ex
**Clarifications:**

Where do we get `warnings` from?

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Provides a fast overview about the amount of manufactured (my parts) and supplier parts (shared parts) and batches, as well as the amount of open investigations and alerts.
**Suggestion:**
Shared contains both numbers, the supplier and the customer number of assets.

```suggestion
Provides a fast overview about the amount of manufactured (my parts) and supplier and customer parts (shared parts) and batches, as well as the amount of open investigations and alerts.
```

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Lists the five most recent quality investigations and alerts to get an overview of the current state.
Worth to mention that
- it lists the **received** notifications only.
- it lists the **active** notifications only, those in state:
  CREATED, SENT, RECEIVED, ACKNOWLEDGED, ACCEPTED, DECLINED

2023-12-20 19:49 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Use the burger menu to use view user details, access the user manual, logout or change the language.
**Suggestion:**

```suggestion
Use the burger menu to view user details, access the user manual, log out or change the language.
```

2024-01-05 11:23 UTC, mauantoniojw approved these changes

2024-01-17 20:34 UTC, hgo-ds requested changes
Double check before merge, there is still need for clarification.
See as well comments in Story https://cofinity-x.atlassian.net/browse/DO-1598.

2024-02-07 15:22 UTC, hgo-ds commented on docs/src/docs/user/user-manual.adoc
> +Provides a fast overview about the amount of manufactured (my parts) and supplier and customer parts (shared parts) and batches, as well as the amount of open investigations and alerts.
**Suggestion:**

Add the direction of the notifications into the documentation.

```suggestion
Provides a fast overview about the amount of manufactured (my parts) and supplier and customer parts (shared parts) and batches, as well as the amount of received open investigations and alerts.
```

2024-08-06 16:55 UTC, closed without merging