Feature/DO-4486 trx concentrate all dependencies and plugins into root pom
Cofinity-X/cofinity-x-ba-traceability-foss pull request #134
Opened 2024-01-15 08:33 UTC by poojapatel23

Moved most of dependencies and plugin from modules pom to root pom

2024-01-15 09:16 UTC, hgo-ds commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/investigation/ReadCreatedInvestigationsInSortedOrderControllerIT.java
> +   // @Test
**Fix:**
Please re enable this test.

2024-01-16 09:50 UTC, hgo-ds requested changes
**Fix:**

Refactor the sections **dependencyManagement** and **dependencies**.

Consider this
- dependencyManagement: Specify the group, artifact and version and/or scope in the parent
- dependencies: Artifacts specified in this section by group and artifact will be included as a dependency in all child modules.

So declare all known dependencies in root-pom dependencyManagement and define only the required ones in the dependencies section of the child module.
---

**Suggestion:**

You might consider to have the same order of the sections in all poms.

2024-01-16 21:03 UTC, poojapatel23 commented on tx-cucumber-tests/pom.xml
> -            <plugin>
done

2024-01-16 21:03 UTC, poojapatel23 commented on tx-cucumber-tests/pom.xml
done

2024-01-16 21:09 UTC, poojapatel23 commented on tx-cucumber-tests/pom.xml
> -            <plugin>
keeping configuration of there two plugins in tx-cucumber-tests not root module

2024-01-16 21:09 UTC, poojapatel23 commented on docs/pom.xml
> -                <artifactId>asciidoctor-maven-plugin</artifactId>
done

2024-01-17 07:48 UTC, poojapatel23 commented on tx-coverage/pom.xml
when I try to replace with variable, I am getting error.
Some problems were encountered while building the effective model for org.eclipse.tractusx.traceability:tx-cucumber-tests:jar:0.0.1-SNAPSHOT
'version' contains an expression but should be a constant. @ org.eclipse.tractusx.traceability:tx-cucumber-tests:${project.version}, ..\cofinity-x-ba-traceability-foss\tx-cucumber-tests\pom.xml, line 33, column 14
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.

2024-01-17 20:12 UTC, hgo-ds requested changes

2024-01-17 20:12 UTC, hgo-ds commented on tx-parent-spring-boot/pom.xml
**Fix:**

Sections `dependencyManagement` and `pluginManagement` can be omitted. Double check with declarations in root-pom.

2024-01-18 11:01 UTC, poojapatel23 commented on pom.xml
@hgo-ds  tx-models means ? tx-cucumber-tests ?

2024-01-18 11:16 UTC, hgo-ds commented on pom.xml
> @hgo-ds tx-models means ? tx-cucumber-tests ?

Yes you are right @poojapatel23 , sry for misleading comment.

2024-01-22 07:10 UTC, mauantoniojw commented
I would park it until we are more clear on the upstream strategy, since this definitely will introduce even more differences.

2024-01-22 09:23 UTC, hgo-ds approved these changes

2024-01-22 09:24 UTC, hgo-ds commented
> I would park it until we are more clear on the upstream strategy, since this definitely will introduce even more differences.

Of course we have to discuss this, and to a certain extent this also applies to all other changes.

2024-08-06 16:55 UTC, closed without merging