[BA-629] Fixed various upstream merge related bugs
Cofinity-X/cofinity-x-ba-traceability-foss pull request #173
Opened 2024-02-23 12:37 UTC by viannbreslerAccso

Fixed various upstream merge related bugs
 
 https://cofinity-x.atlassian.net/browse/BA-629
 https://cofinity-x.atlassian.net/browse/BA-628
 https://cofinity-x.atlassian.net/browse/BA-621
 https://cofinity-x.atlassian.net/browse/BA-671

2024-02-23 13:55 UTC, rogocof requested changes

2024-02-23 13:55 UTC, rogocof commented on cfx-frontend/src/assets/locales/en/common.json
> +      "sentactiveinvestigations": "Sent Active Investigations",
is this camelCase typo upstream related?

2024-02-26 06:04 UTC, viannbreslerAccso commented on cfx-frontend/src/assets/locales/en/common.json
> +      "sentactiveinvestigations": "Sent Active Investigations",
Yes, that comes from upstream

2024-02-26 09:16 UTC, viannbreslerAccso commented on cfx-frontend/src/assets/locales/en/common.json
> +      "sentactiveinvestigations": "Sent Active Investigations",
That seems to be a git issue. Git normally doesn't recognize case changes. I'll fix it now

2024-02-26 13:42 UTC, rogocof approved these changes

2024-02-27 06:03 UTC, merged