[BA-687] fix table filter description
Cofinity-X/cofinity-x-ba-traceability-foss pull request #174
Opened 2024-02-28 11:46 UTC by viannbreslerAccso

Fixed the following broken filters

https://cofinity-x.atlassian.net/browse/BA-625
https://cofinity-x.atlassian.net/browse/BA-624
https://cofinity-x.atlassian.net/browse/BA-623

2024-02-28 12:02 UTC, rogocof requested changes

2024-02-28 12:02 UTC, rogocof commented on cfx-frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html
> +      }}
remove that line break please

2024-02-28 12:02 UTC, rogocof commented on cfx-frontend/src/app/modules/shared/model/filter-config.ts
> +      value: 'LIFE_THREATENING',
Why not Severity.LIFE_THREATENING?

2024-02-28 12:05 UTC, viannbreslerAccso commented on cfx-frontend/src/app/modules/shared/model/filter-config.ts
> +      value: 'LIFE_THREATENING',
Because the API is expecting 'LIFE_THREATENING', using Severity.LIFE_THREATENING would give 'LIFE-THREATENING'

2024-02-28 12:06 UTC, rogocof commented on cfx-frontend/src/app/modules/shared/model/filter-config.ts
> +      value: 'LIFE_THREATENING',
understood

2024-02-29 08:27 UTC, rogocof approved these changes

2024-02-29 08:45 UTC, merged