[BA-793] Implementation of Toast UX Designs
Cofinity-X/cofinity-x-ba-traceability-foss pull request #198
Opened 2024-03-19 06:44 UTC by viannbreslerAccso

Implemented UX Designs for toast
Fixed Table settings reset button being visible on dashboard tables: https://cofinity-x.atlassian.net/browse/BA-794

2024-03-19 08:40 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "successfullyAcceptedTitle": "Untersuchung erfolgreich akzeptieren",
```suggestion
      "successfullyAcceptedTitle": "Untersuchung akzeptieren",
```

2024-03-19 08:42 UTC, felixschmidtcofinity commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedCloseTitle": "Enge Untersuchung fehlgeschlagen",
```suggestion
      "failedCloseTitle": "Schließen der Untersuchung fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof requested changes

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedAcknowledgeTitle": "Quittierung der Warnung fehlgeschlagen",
```suggestion
      "failedAcknowledgeTitle": "Bestätigen fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedApproveTitle": "Warnung genehmigen fehlgeschlagen",
```suggestion
      "failedApproveTitle": "Genehmigen fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedCanceTitle": "Warnung abbrechen fehlgeschlagen",
```suggestion
      "failedCanceTitle": "Abbrechen fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedCloseTitle": "Warnung schließen fehlgeschlagen",
```suggestion
      "failedCloseTitle": "Schließen fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedDeclineTitle": "Ablehnende Warnung fehlgeschlagen"
```suggestion
      "failedDeclineTitle": "Ablehnung fehlgeschlagen"
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedApproveTitle": "Genehmigung der Untersuchung gescheitert",
```suggestion
      "failedApproveTitle": "Genehmigung der Untersuchung fehlgeschlagen",
```

2024-03-19 09:10 UTC, rogocof commented on cfx-frontend/src/assets/locales/de/common.json
> +      "failedCancelTitle": "Untersuchung abbrechen gescheitert",
```suggestion
      "failedCancelTitle": "Untersuchung abbrechen fehlgeschlagen",
```

2024-03-19 10:17 UTC, viannbreslerAccso commented
@rogocof Thanks, I made all the required changes

2024-03-20 10:37 UTC, rogocof approved these changes

2024-03-20 10:39 UTC, merged