Chore/dev with 10.7.0
Cofinity-X/cofinity-x-ba-traceability-foss pull request #212
Opened 2024-03-25 10:32 UTC by poojapatel23

- merged new release 10.7.0 with cofinity dev branch
- fixed integration test
- fixed unit test case
- fixed testdata according to new release
- fixed wiremock issues related to irsPolicies
- fixed edc/management/v2/assert part from application.yml file

2024-04-16 11:56 UTC, rogocof approved these changes

2024-04-17 11:41 UTC, rogocof requested changes
I get following error in integration test:
`[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AssetAsPlannedControllerSortValuesIT.givenSortArguments_whenCallSortEndpoint_thenReturnExpectedResponse:86 1 expectation failed.
JSON path content.idShort doesn't match.
Expected: iterable containing ["ZBZELLE", "HVModul", "OEMAHighVoltageBattery", "VehicleModelA", "TierBECU1", "SubTierASensor", "TierAGearbox", "NTierACathodeMaterial", "NTierAPlastics", "NTierANTierProduct", "SubTierBSealant", "SubTierBGlue"] in relative order
  Actual: <[ZBZELLE, OEMAHighVoltageBattery, HVModul, VehicleModelA, TierBECU1, SubTierASensor, TierAGearbox, NTierACathodeMaterial, NTierAPlastics, NTierANTierProduct, SubTierBSealant, SubTierBGlue]>

[INFO] 
[ERROR] Tests run: 620, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
`

2024-04-18 06:03 UTC, viannbreslerAccso requested changes
![asBuilt](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/6d6e9ee2-7c64-4889-933e-7516471a93f0)

It is working now with help from Robin, but in the app the as built tables throw errors, I suspect you just need to update the frontend files to the latest on dev

2024-04-19 08:19 UTC, viannbreslerAccso approved these changes

2024-04-19 15:02 UTC, rogocof approved these changes

2024-04-22 07:10 UTC, merged