[BA-11] TRX_Forward Investigations and Alerts
Cofinity-X/cofinity-x-ba-traceability-foss pull request #219
Opened 2024-04-04 07:27 UTC by rogocof

2024-04-04 08:01 UTC, viannbreslerAccso commented
Please see a few visual issues I found

I'm unable to find the forward investigation link?

![noForwardLink](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/e57aad3e-1d23-47b7-af82-095f154cc3c2)

2024-04-04 08:02 UTC, viannbreslerAccso commented
The tables are no longer scrollable, instead is shows the full height

![tableSizeBroken](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/1028fe1e-955c-4fd9-89cb-358f412300a9)

2024-04-04 08:03 UTC, viannbreslerAccso commented
The buttons in the last step of the request stepper have broken styling

![Review2](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/8f0ca4fd-392c-4ab6-9de4-24ada87ea348)
![Review1](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/0bafbd34-ed12-4bcd-a2e6-5fcf5c63a562)

2024-04-04 08:09 UTC, viannbreslerAccso commented
Please check there is a linting error. You can see this with the command >yarn lint:check

2024-04-04 08:10 UTC, viannbreslerAccso commented
Please check there are some failing unit tests

2024-04-04 08:15 UTC, viannbreslerAccso commented
The successful investigation toast is no longer showing

2024-04-04 08:40 UTC, viannbreslerAccso requested changes
Done for now, it looks good so far. Will continue once I'm able to see the forward investigation link

2024-04-04 08:40 UTC, viannbreslerAccso commented on cfx-frontend/src/app/modules/shared/components/request-notification/request-notification.base.scss
> +  min-height: 300px;
This might be breaking the styling of the request-stepper buttons mentioned in my comment

2024-04-04 08:40 UTC, viannbreslerAccso commented on cfx-frontend/src/app/modules/shared/components/request-notification/forward-notification/forward-notification.component.ts
> +
Please remove this empty line

2024-04-04 10:38 UTC, viannbreslerAccso commented
![styling](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/4f0d3470-6bb8-4d69-8d3b-1584bd806ce5)

Please look at the following things:

1. The word and styling is incorrect
2. The severity and description labels get cut-off
3. There is a missing phrase here
4. The padding on the sides of the buttons are inconsistent

* The description text-area should probably be read-only?

2024-04-04 10:41 UTC, viannbreslerAccso commented
![bottomCutOff](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/0f8a8609-35a5-4509-92b0-ed2b55401455)

On my laptop screen I'm unable to see the buttons at the bottom without zooming out. Consider making the dialog content scrollable by giving it a max-height with overflow-y: auto

2024-04-04 10:45 UTC, viannbreslerAccso commented
When adding the investigation to the queue the toast displays that an investigation for 1 part was added even though multiple parts were selected

![1part](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/cff1f701-986c-4581-8cc8-0a41e8834054)

2024-04-05 12:20 UTC, rogocof commented on cfx-frontend/src/app/modules/shared/components/request-notification/request-notification.base.scss
> +  min-height: 300px;
done

2024-04-05 12:21 UTC, rogocof commented on cfx-frontend/src/app/modules/shared/components/request-notification/forward-notification/forward-notification.component.ts
> +
done

2024-04-05 12:23 UTC, rogocof commented
> ![styling](https://private-user-images.githubusercontent.com/134606480/319548028-4f0d3470-6bb8-4d69-8d3b-1584bd806ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjAwNzQsIm5iZiI6MTcxMjMxOTc3NCwicGF0aCI6Ii8xMzQ2MDY0ODAvMzE5NTQ4MDI4LTRmMGQzNDcwLTZiYjgtNGQ2OS04ZDNiLTE1ODRiZDgwNmNlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxMjIyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGFlZGYxZDc0ZmFlMTgyNTAwMTY0ZGEwZGYxOGY0NjE0NDk1NDQ2OWZkMTM2OTcwYjA4ZmZmMjE2MzZiODI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qMDHBswRM6tt7x-rMBYHz0iXRrLm8Gi1D1l5nfNWT7k)
> 
> Please look at the following things:
> 
> * [x]  1. The word and styling is incorrect
> * [x]  2. The severity and description labels get cut-off
> * [x]  3. There is a missing phrase here
> * [x]  4. The padding on the sides of the buttons are inconsistent
> * [ ]  * The description text-area should probably be read-only?
> * [ ]  * The "show" box is cut-off at the bottom

According to ticket, it should be editable. Please explain last point.

2024-04-09 06:42 UTC, viannbreslerAccso commented
> > ![styling](https://private-user-images.githubusercontent.com/134606480/319548028-4f0d3470-6bb8-4d69-8d3b-1584bd806ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjAwNzQsIm5iZiI6MTcxMjMxOTc3NCwicGF0aCI6Ii8xMzQ2MDY0ODAvMzE5NTQ4MDI4LTRmMGQzNDcwLTZiYjgtNGQ2OS04ZDNiLTE1ODRiZDgwNmNlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxMjIyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGFlZGYxZDc0ZmFlMTgyNTAwMTY0ZGEwZGYxOGY0NjE0NDk1NDQ2OWZkMTM2OTcwYjA4ZmZmMjE2MzZiODI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qMDHBswRM6tt7x-rMBYHz0iXRrLm8Gi1D1l5nfNWT7k)
> > Please look at the following things:
> > 
> > * [x]   1. The word and styling is incorrect
> > * [x]   2. The severity and description labels get cut-off
> > * [x]   3. There is a missing phrase here
> > * [x]   4. The padding on the sides of the buttons are inconsistent
> > * [ ]   * The description text-area should probably be read-only?
> > * [ ]   * The "show" box is cut-off at the bottom
> 
> According to ticket, it should be editable. Please explain last point.

The Show box of the paginator is cut-off at the bottom. This seems to be affected by screen sizes. Sometimes it's fine and sometimes it's not

2024-04-09 06:44 UTC, viannbreslerAccso commented
![bottomCutOff2](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/8e5b40ea-e5b0-4e3b-84b5-f23b08afd5d3)

The dialog is still cut-off at the bottom with no way to reach the buttons without zooming out.

2024-04-09 06:45 UTC, viannbreslerAccso commented
![padding and CutOff](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/8b896dee-2129-428b-8fad-19cd279ed3c1)

The request stepper has incorrect padding and is also cut-off at the bottom of the screen

2024-04-09 06:46 UTC, viannbreslerAccso commented
![noPartSelected](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/968621b9-3f44-4002-adda-1f1cfcd0eb85)

It is possible to "Add to queue" without selecting any parts

2024-04-09 10:07 UTC, viannbreslerAccso approved these changes

2024-04-09 10:10 UTC, merged