[BA-783] UX Review changes for browser size responsiveness
Cofinity-X/cofinity-x-ba-traceability-foss pull request #223
Opened 2024-04-10 11:48 UTC by viannbreslerAccso

Made changes to the responsiveness to browser size required by UX review

2024-04-10 15:02 UTC, rogocof commented
Please check the Footer bar for bigger screens 
![screenshot_ba783](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/158559825/e5813e19-32b9-45c0-aa25-8d41f73bec3c)

2024-04-10 15:06 UTC, rogocof requested changes

2024-04-10 15:06 UTC, rogocof commented on cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.scss
> +  @media (max-width: 1024px) {
what is the reason for this value?

2024-04-10 15:06 UTC, rogocof commented on cfx-frontend/src/theme/base.scss
> +      max-width: 1152px;
what is the reason for this value?

2024-04-11 08:46 UTC, viannbreslerAccso commented on cfx-frontend/src/theme/base.scss
> +      max-width: 1152px;
This is 1200 - 24 -24 (padding on sides)
1200px is used, because elements start to break apart if 1024 is used.

2024-04-11 08:50 UTC, viannbreslerAccso commented on cfx-frontend/src/app/modules/page/dashboard/presentation/dashboard.component.scss
> +  @media (max-width: 1024px) {
I removed this, because the media query was unnecessary

2024-04-11 08:54 UTC, viannbreslerAccso commented on cfx-frontend/src/app/modules/core/layout/footer/footer.component.scss
> +    min-width: 1072px;
This has been removed

2024-04-11 11:34 UTC, rogocof approved these changes
Thanks for the fix. I checked locally and it looks good!

2024-04-11 11:35 UTC, merged