[DO-1499] Implement my parts designs
Cofinity-X/cofinity-x-ba-traceability-foss pull request #23
Opened 2023-11-02 07:31 UTC by viannbreslerAccso

Implementation of the my parts figma desgins

2023-11-02 15:34 UTC, JoelDietz requested changes
The following things need still to be changed:

1. Select 2 lifecycle stages boarder color should be 4d4d4d but is rgba(0, 0, 0, 0.87)
2. Checkbox unselected unhovered boarder color should be #808080 but is rgba(0,0,0,0.38)
3. priority high between select and ID should be color #808080 but is black
4. Search bar boarder seems a different color but could not find the color used but it should be #DFDFDF
5. Search bar placeholder text seems a different color but could not find the color used but it should be #808080
6. The pagination overlays with the my parts detail page and the backdrop.

2023-11-02 15:34 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/card-icon/card-icon.component.html
The alt tag should maybe filled with the name of the icon

2023-11-02 15:34 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/input/input.component.html
The alt tag should maybe filled with the name of the icon

2023-11-02 15:34 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/parts-table/parts-table.component.html
Just a remark the deleted Filtering has to be added back in but in changed form. But that will be done in an separate task when it got its new form.

2023-11-02 15:34 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/severity/severity.component.html
The alt tag should maybe filled with the name of the icon

2023-11-03 06:00 UTC, viannbreslerAccso commented on frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
Done

2023-11-03 06:01 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/card-icon/card-icon.component.html
Done

2023-11-03 06:01 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/input/input.component.html
Done

2023-11-03 06:01 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/severity/severity.component.html
Done

2023-11-03 13:23 UTC, JoelDietz approved these changes

2023-11-03 13:25 UTC, merged