Feature/do 3634 quality alerts api with filtering option based on local setup branch
Cofinity-X/cofinity-x-ba-traceability-foss pull request #25
Opened 2023-11-07 09:17 UTC by ramnarayan-cofinityx

2023-11-08 10:50 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertSpecification.java
> +        }
The implementation was based on the tractusx's org.eclipse.tractusx.traceability.common.repository.BaseSpecification
 which follows Local Date comparison approach. 

Moreover, there are inconsistencies in the Date types of createdDate and updatedDate used in org.eclipse.tractusx.traceability.qualitynotification.infrastructure.model.NotificationBaseEntity (Instant) and 
org.eclipse.tractusx.traceability.qualitynotification.infrastructure.model.QualityNotificationMessageBaseEntity (LocalDateTime)

2023-11-08 10:51 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/repository/InvestigationSpecification.java
> +        return null;
same explanation for alert goes for this code snippet as well

2023-11-08 17:34 UTC, hgo-ds requested changes
Adding integration tests for different filter configurations in `org.eclipse.tractusx.traceability.integration.qualitynotification.[alert|investigation]` for alerts and investigations is highly recommended.

2023-11-09 08:38 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertSpecification.java
> +        Path predicatePath = null;
Use Ternary operator

2023-11-09 08:40 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/repository/InvestigationSpecification.java
> +        Path predicatePath = null;
Use Ternary operator

2023-11-09 08:47 UTC, ramnarayan-cofinityx commented
Add the integration tests for Alerts and Investigations Search criteria APIs

2023-11-09 11:00 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/base/service/QualityNotificationService.java
>      PageResult<QualityNotification> getCreated(Pageable pageable);
Removing this method needs to be proposed to upstream team.

2023-11-10 11:27 UTC, ramnarayan-cofinityx commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/domain/investigation/service/InvestigationServiceImplTest.java
I have added the integration test covering date based attributes

2023-11-10 19:43 UTC, hgo-ds reviewed
**Fix:** Adjust error message to 

`"Invalid filter param provided filter={provided} expected format is following filter=parameter,operation,value"` (**filter** instead of sort)

in

https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/blob/9147b2473f09b2ba3aa15d305c6777def5ecdce0/tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/SearchCriteriaRequestParam.java#L71

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertSpecification.java
> +        Join<AlertEntity, AlertNotificationEntity> investigationJoin = root.join("notifications");
**Fix:**
```suggestion
        Join<AlertEntity, AlertNotificationEntity> alertJoin = root.join("notifications");
```

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertSpecification.java
> +        Path predicatePath = (ATTRIBUTES_IN_ALERT_ENTITY.contains(criteria.getKey())) ?
**Fix:**
Brackets are superfluous
```suggestion
        Path predicatePath = ATTRIBUTES_IN_ALERT_ENTITY.contains(criteria.getKey()) ?
```

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/repository/InvestigationSpecification.java
> +        Path predicatePath = (ATTRIBUTES_IN_INVESTIGATION_ENTITY.contains(criteria.getKey())) ?
**Fix:**
Brackets are superfluous

```suggestion
        Path predicatePath = ATTRIBUTES_IN_INVESTIGATION_ENTITY.contains(criteria.getKey()) ?
```

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/ReadAlertsControllerIT.java
> +        AlertEntity firstInvestigation = AlertEntity.builder()
**Fix:** use proper naming

```suggestion
        AlertEntity firstAlert = AlertEntity.builder()
```

applies to all the creations in this class.

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/ReadAlertsControllerIT.java
**Fix:**

This class is far too long.

Fix by extracting _given_ boilerplate code for creating and storing the alerts to some central reusable code instead of copying it into every method.

Move all AlertFilterIT tests into separate test-class, i.e. `FilterAlertsControllerIT` or even two classes, one for `receive` and one for `create`.

2023-11-10 19:43 UTC, hgo-ds commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/investigation/ReadInvestigationsControllerIT.java
**Fix:**

This class is far too long.

Fix by extracting given boilerplate code for creating and storing the investigations to some central reusable code instead of copying it into every method.

Move all InvestigationFilterIT tests into separate test-class, i.e. `FilterInvestigationsControllerIT` or even two classes, one for `receive` and one for `create`.

2023-11-13 15:51 UTC, ramnarayan-cofinityx reviewed
Integration tests have been implemented

2023-11-13 15:51 UTC, ramnarayan-cofinityx commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/repository/AlertSpecification.java
> +        }
Timezone based date comparison will be handled in future sprint based on the priority of the story

2023-11-13 17:25 UTC, hgo-ds approved these changes

2023-11-14 10:15 UTC, merged