[DO-1258] Quality alert details page
Cofinity-X/cofinity-x-ba-traceability-foss pull request #37
Opened 2023-11-14 12:05 UTC by viannbreslerAccso

Implementation of the quality alert figma designs

2023-11-14 19:37 UTC, JoelDietz requested changes
Please check the status of the quality alerts overlays again (or are they part of a different ticket, that was not part of this sprint?)
Also there is a problem with the back button (leaving the detail page) see comment. And last the cancel button we wondered in the review about should be only visible when the approve button is also visible. (see the corresponding comment.)
Everything else looks good.

2023-11-15 05:55 UTC, viannbreslerAccso commented on frontend/src/assets/locales/en/common.json
Done

2023-11-15 05:55 UTC, viannbreslerAccso commented on frontend/src/assets/locales/en/common.json
>        "approvalTitle": "Approval of alert",
Done

2023-11-15 05:55 UTC, viannbreslerAccso commented on frontend/src/assets/locales/en/common.json
>        "closeTitle": "Close of alert",
Done

2023-11-15 05:57 UTC, viannbreslerAccso commented on frontend/src/app/modules/page/alerts/detail/alert-detail.component.html
> +  <div class="buttons-container">
Done - Yes, I forgot to uncomment the ngIf

2023-11-15 06:10 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.scss
>    &-icon {
Done - That css is meant for the icon. But I updated the 10px to 12px of the other section which fixed the size of the text next to the clock icon

2023-11-15 07:31 UTC, JoelDietz commented on frontend/src/app/modules/page/alerts/detail/alert-detail.component.html
> +    <img class="close-button"
Is a browser thing. In chrome it works and in firefox it does not

2023-11-15 07:58 UTC, JoelDietz approved these changes

2023-11-15 08:00 UTC, merged