[DO-3633] Filtering for the pages MyParts and Quality Alerts
Cofinity-X/cofinity-x-ba-traceability-foss pull request #40
Opened 2023-11-14 17:42 UTC by JoelDietz

Created the filtering for the Quality Alerts page and touched up the filtering on the MyParts page to fit the design and wished functionality.

2023-11-15 06:41 UTC, viannbreslerAccso commented
![DateBold](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/2b3e5100-692e-49db-8695-b1d20d971a2a)

The font style of the month should be bold

2023-11-15 06:42 UTC, viannbreslerAccso commented
![TableLinesAfterRefresh](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/8e3de18a-0d43-42ea-ade7-c491743c0301)

After a refresh there are lines on each row in the table. This means there are some conflicting css somewhere

2023-11-15 06:43 UTC, viannbreslerAccso commented
![autocompleteArrow](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/b427eeda-41ab-4d4a-9815-363a484e86ef)

The arrow icon is incorrect and needs to sit next to the column header

2023-11-15 06:44 UTC, viannbreslerAccso commented
![ArrowPosition](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/4d494215-e82b-4763-8295-6358f4fdf459)

The arrow icon is incorrect and needs to move to next to the column name

2023-11-15 07:13 UTC, viannbreslerAccso commented
Not all of the filters work in the my parts page

2023-11-15 07:18 UTC, viannbreslerAccso requested changes

2023-11-15 07:18 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.spec.ts
>  describe('MultiSelectAutocompleteComponent', () => {
Please fix these tests if possible

2023-11-15 07:18 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts
Please don't fix the indentation in the future

2023-11-15 07:39 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts
That happend because of the merge with the my parts page. But yes we talked about that.

2023-11-15 11:32 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html
> +        >{{ option[display] }}</mat-checkbox
Done

2023-11-15 11:32 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html
> +        >All</mat-checkbox
Done

2023-11-15 11:32 UTC, JoelDietz commented on frontend/src/app/modules/page/parts/presentation/parts.component.ts
> +    | AssetAsRecycledFilter;
Done

2023-11-15 11:33 UTC, JoelDietz commented on frontend/src/app/modules/page/alerts/presentation/alerts.component.ts
> +      display: 'Life-Threatening',
Done (now using the correct i18n call to get the correct naming.

2023-11-15 11:34 UTC, JoelDietz commented on frontend/src/app/modules/page/alerts/presentation/alerts.component.ts
> +import { Severity } from '@shared/model/severity.model';
Now again in use

2023-11-15 11:49 UTC, viannbreslerAccso commented
![GapA](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/a79c763a-c164-43f0-b7c1-74cc60eb0c1d)

There is a big gap tween the selection box and the ! column

2023-11-15 11:50 UTC, viannbreslerAccso commented
![ArrowBelow](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/c1865ce8-4f75-4dda-b4c0-1ce89f8f7dbb)

There arrow direction is below and not right of the column

2023-11-15 11:50 UTC, viannbreslerAccso commented
The arrow does not change when clicked (Up, Down)

2023-11-15 11:51 UTC, viannbreslerAccso commented
The country column doesn't seem to sort

2023-11-17 07:48 UTC, viannbreslerAccso commented
![delete](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/f79fafc7-f3fb-4c28-ab16-c6f00ca57999)
![create alerts](https://github.com/Cofinity-X/cofinity-x-ba-traceability-foss/assets/134606480/b494cc77-a5a3-494b-9d06-24dc09f9703b)

I found these two issues after the latest commit

2023-11-17 10:59 UTC, viannbreslerAccso approved these changes

2023-11-17 11:10 UTC, merged