[DO-1596][minor] Implement create investigations page
Cofinity-X/cofinity-x-ba-traceability-foss pull request #66
Opened 2023-11-29 07:55 UTC by viannbreslerAccso

Implement create quality investigations designs

2023-11-29 12:01 UTC, JoelDietz requested changes
1. assets/images/icons/undefined.svg call gets made on pressing the "Add to queue" button 
but that request fails for the asset can not be found.
2. When I remove a part from the chip list its selection does not get removed in the table, but if i close the start investigation window and reopen it stays removed but marked selected. On the my parts page this works for the create alerts.

2023-11-30 06:54 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
That is because the date min date is set to "AtLeastNow" =>

  targetDate: new FormControl(null, [DateValidators.atLeastNow()]),

2023-11-30 07:07 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
I think it would be better instead of showing an error to just disable the dates before today. And show the error only if he enters an invalid time.

2023-11-30 07:19 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
Also the minimum date is set here:   public readonly minDate = new Date(); in request-notification-base.ts

2023-11-30 07:57 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
done

2023-11-30 07:57 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
Done

2023-11-30 08:06 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/dateTime/dateTime.component.html
I am using the same designs, except for the buttons, because this not the same component, It's a ngx-mat-datetime-picker which doesn't have an actions container

2023-11-30 08:52 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/components/dateTime/dateTime.component.html
Done - I can't seem to disable the focus effect, but it's centered now

2023-11-30 12:45 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/request-notification/request-investigation.component.ts
When setting the min date to now the selection for the time is not blocked for going to an invalid time. But the button is not clickable without a info why. maybe set the min date to 00:00 h then you can select any time of that day and afterwards it says please take another time. 
Or if it is possible it  could block the time selection two? (in the later option it should be looked into creating a new min date every time the date picker is opened. Else you could select a time no longer valid because the old min date when opening the request window but the validation says now afterwards.)

2023-11-30 13:37 UTC, JoelDietz approved these changes

2023-11-30 13:38 UTC, merged