[DO-1292] Implement Quality investigations on dasbhboard
Cofinity-X/cofinity-x-ba-traceability-foss pull request #8
Opened 2023-10-12 11:35 UTC by viannbreslerAccso

Implemented quality investigations on dashboard. Most of the work was done in https://cofinity-x.atlassian.net/browse/DO-1293

2023-10-12 13:36 UTC, JoelDietz requested changes
Just a thing i notice on:
https://www.figma.com/proto/weOyZR5alPayKCyudUnUDb/Cofinity-X-Application?type=design&node-id=1-2&t=4CbHQESgeewKVWes-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2

2023-10-12 13:36 UTC, JoelDietz commented on frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
Not sure where but when you hover over an item the statuses closed, canceled and declined should change the colors. (Most likely also on the quality alerts but there is no preview.) (see "present" on figma)

2023-10-13 06:27 UTC, viannbreslerAccso commented on frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
This seems to be an oversight on the design side

Sarah replied: "thanks for mentioning this. No, the status labels should stay static as they are with no whatsoever interaction."

2023-10-13 07:10 UTC, JoelDietz approved these changes

2023-10-13 07:11 UTC, merged