[DO-1535] Implementation of  my parts details
Cofinity-X/cofinity-x-ba-traceability-foss pull request #80
Opened 2023-12-06 09:00 UTC by viannbreslerAccso

Implemented UX designs for the my Parts details page
Fixed "Alert ID" also showing in Investigation details action pages

2023-12-07 09:31 UTC, mauantoniojw requested changes

2023-12-07 09:31 UTC, mauantoniojw commented on frontend/src/app/modules/page/parts/parts.routing.ts
> +  const PARTS_ROUTING: Routes = [
why is this change for? seems just an indentation?

2023-12-07 09:31 UTC, mauantoniojw commented on frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.html
> +<!-- <mat-accordion class="example-headers-align"
can we remove the commented code?

2023-12-08 10:17 UTC, mauantoniojw commented on .gitignore
> +/mvnw.cmd
remove this

2023-12-08 10:23 UTC, mauantoniojw requested changes
pls check some comments

2023-12-08 10:23 UTC, viannbreslerAccso commented on frontend/src/app/modules/page/parts/parts.routing.ts
> +  const PARTS_ROUTING: Routes = [
Yes, no change to this file. This was just my formatter fixing it while I was trying out a few things. I didn't realize this happened though

2023-12-08 10:24 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/modules/part-details/presentation/part-detail.component.html
> +<!-- <mat-accordion class="example-headers-align"
This has changed, I added a TODO, because this will still need to be addressed with the implementation of the "Investigations for component" tab

2023-12-08 11:14 UTC, merged