[DO-1585]  Implementation of Shared parts details
Cofinity-X/cofinity-x-ba-traceability-foss pull request #85
Opened 2023-12-11 06:55 UTC by viannbreslerAccso

Implemented the shared parts details figma designs
Added functionality to be able to click on a table row as a shortcut to view details

2023-12-11 12:01 UTC, JoelDietz requested changes
As already told the following parts I noticed:
1. Error when going on the full screen when on a asPlanned part: Backend returned code undefined: Asset with id urn:uuid:cce342a3-910f-4802-b8a2-c37c59344cf2 was not found.
2. After going on the Investigation for components tab I can't change back to the parts detail tab. 
3. .mvn files and backend/openapi files included.

2023-12-11 12:16 UTC, mauantoniojw requested changes

2023-12-11 12:16 UTC, mauantoniojw commented on .mvn/wrapper/maven-wrapper.jar
this can be removed

2023-12-11 12:16 UTC, mauantoniojw commented on .mvn/wrapper/maven-wrapper.properties
this can be removed

2023-12-11 12:16 UTC, mauantoniojw commented on mvnw
this can be removed

2023-12-11 12:16 UTC, mauantoniojw commented on mvnw.cmd
this can be removed

2023-12-11 12:16 UTC, mauantoniojw commented on tx-backend/openapi/traceability-foss-backend.json
this can be removed

2023-12-11 12:16 UTC, mauantoniojw commented on tx-backend/openapi/traceability-foss-backend.json.rej
this can be removed

2023-12-11 19:07 UTC, hgo-ds commented on .mvn/wrapper/maven-wrapper.jar
Veto, we probably need this and all the related files in the `.mvn` folder for those who don't have maven installed to be able to build the application.
Please double check.

Should be probably moved into project root.

2023-12-11 19:34 UTC, hgo-ds commented on tx-backend/openapi/traceability-foss-backend.json
> this can be removed

Well, this file is generated by `OpenApiDocumentationIT` during integration tests of module tx-backend.

If we want to remove it, we should also donate a suitable `.gitgnore` in folder `tx-backend`:

`
openapi/
`

Choosing a different destination could be an additional option.

2023-12-11 19:45 UTC, hgo-ds commented on tx-backend/openapi/traceability-foss-backend.json.rej
Yes, this file is a rejected files and certainly needs to be removed.

2023-12-11 20:16 UTC, hgo-ds commented on tx-backend/openapi/traceability-foss-backend.json
> this can be removed

Well, this file is generated by `OpenApiDocumentationIT` during integration tests of module tx-backend.

If we want to remove it, we should also donate a suitable `.gitgnore` in folder `tx-backend`:

`
openapi/
`

Choosing a different destination could be an additional option.

2023-12-12 09:00 UTC, mauantoniojw approved these changes

2023-12-12 09:06 UTC, JoelDietz approved these changes

2023-12-12 09:08 UTC, merged