[DO-1294][minor] filtering ux review comment changes
Cofinity-X/cofinity-x-ba-traceability-foss pull request #87
Opened 2023-12-11 15:17 UTC by JoelDietz

Changes requested in the ux review. Following changes where implemented:
Sarahs comment on the [ticket](https://cofinity-x.atlassian.net/browse/DO-1294):
2. b, c, d
3. a 
4. b, c 

As for 1. is not yet designed and 3. b, c and 4.a are separate tickets for the back end.

to 3.a and 4.c there is only a delay as long as you are inside the input field. if you leave it and something changed the new filter is triggered.

2023-12-12 10:59 UTC, viannbreslerAccso requested changes
- Typing the date in the filter box does not seem to do anything
- The searchbar doesn't seem to work? The results are always empty (tested in investigations tab)
- Sorting by multiple statuses is not working

2023-12-12 11:02 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> -  encapsulation: ViewEncapsulation.None,
cool

2023-12-12 11:29 UTC, mauantoniojw requested changes

2023-12-12 11:29 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +          this.dateManuelSelectionEvent(next);
typo

2023-12-12 11:29 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +    if (column[column.length - 1].toUpperCase() === 'MINOR') {
can we remove the way we are using this? it is too much overhead to have these something.somethingelse.

now we are makeing some workarouns also because of that, perhaps something simpler:
```
    {
      value: 0,
      checked: false,
      severity: Severity.MINOR,
    }
    ```

then we should remove as much code as possible

2023-12-12 11:29 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +      this.severityIconName[column.join('.')] = 'LIFE-THREATENING';
all these joins too, will be removed.

2023-12-12 11:29 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +  public onDeselect(inputfield: string): void {
onBlur seems like a better name

2023-12-12 11:29 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +    }
```
    if (this.runningTimer) {
      clearTimeout(this.inputTimer);
      if (inputfield === 'textFilter') {
        this.triggerFiltering(true);
      } else if (inputfield === 'dateFilter') {
        this.dateManuelSelectionEvent(this.searchDate.value);
      } else if (inputfield === 'selectionFilter') {
        this.triggerFiltering(false);
      }
    }
```

2023-12-12 14:17 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +          this.dateManuelSelectionEvent(next);
DONE

2023-12-12 14:17 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +      this.severityIconName[column.join('.')] = 'LIFE-THREATENING';
done

2023-12-12 14:18 UTC, JoelDietz commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +  public onDeselect(inputfield: string): void {
yes it does. 
Done

2023-12-14 08:02 UTC, viannbreslerAccso requested changes

2023-12-14 08:02 UTC, viannbreslerAccso commented on frontend/src/app/modules/shared/helper/custom-date-adapter.ts
> +    console.log(displayFormat);
Please remove this console log

2023-12-14 08:58 UTC, viannbreslerAccso approved these changes

2023-12-14 10:02 UTC, mauantoniojw commented on frontend/src/app/modules/shared/components/notification-overview/notification-overview.component.scss
> -  @apply border-0 uppercase inline-flex items-center px-3 py-0.5 rounded-full font-semibold text-xs w-fit;
cool

2023-12-14 10:02 UTC, mauantoniojw commented on frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.scss
> -.notification-status {
niceee

2023-12-14 10:02 UTC, mauantoniojw approved these changes

2023-12-14 10:29 UTC, merged